### ISSUE TITLE
Many Pending Executions Cerberus1.1.11-SNAPSHOT-1105

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1213]
Hello,

We've launched PREPROD Campaign for Cerberus1.1.11-SNAPSHOT-1105 but we had to cancel it at the begging as there was many pending executions calculating URL_CLEAR_BASKET that is a text property that calculates one Account and open URL to clear basket.

http://192.168.134.197/CerberusQA/ReportingExecutionByTag.jsp?Tag=WEB_PREPROD_Cerberus1.1.11-SNAPSHOT-1105

Can you take a look?
Thanks
Best Regards

**Comment by j0hnsa** [comment]
Example of a pending exec:
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=42911047

**Comment by gmoita** [comment]
On the logs, when running, I have the following error on the glassfish logs:
[#|2017-03-01T16:27:04.987+0100|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=124;_ThreadName=Thread-2;|2017-03-01 16:27:04 ERROR RunTestCase:343 - Error while executing RunTestCase
java.lang.NullPointerException
        at org.cerberus.service.datalib.impl.DataLibService.filterWithNatureNOTINUSE(DataLibService.java:374)
        at org.cerberus.service.datalib.impl.DataLibService.filterWithNature(DataLibService.java:223)
        at org.cerberus.service.datalib.impl.DataLibService.getFromDataLib(DataLibService.java:164)
        at org.cerberus.engine.gwt.impl.PropertyService.property_getFromDataLib(PropertyService.java:1171)
        at org.cerberus.engine.gwt.impl.PropertyService.calculateProperty(PropertyService.java:590)
        at org.cerberus.engine.gwt.impl.PropertyService.decodeStringWithExistingProperties(PropertyService.java:195)
        at org.cerberus.engine.gwt.impl.VariableService.decodeStringCompletly(VariableService.java:103)
        at org.cerberus.engine.gwt.impl.ActionService.doAction(ActionService.java:152)
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeAction(ExecutionRunService.java:726)
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeStep(ExecutionRunService.java:672)
        at org.cerberus.engine.execution.impl.ExecutionRunService.executeTestCase(ExecutionRunService.java:416)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
        at com.sun.proxy.$Proxy190.executeTestCase(Unknown Source)
        at org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:73)
        at org.cerberus.servlet.zzpublic.RunTestCase.doGet(RunTestCase.java:340)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
        at com.sun.grizzly.http.ajp.AjpProcessorTask.invokeAdapter(AjpProcessorTask.java:135)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)

**Comment by bcivel** [comment]
fixed with this commit 581bd12
You should not have PE as final status anymore, nor server not stopped.

**Comment by mbessa** [comment]
Hello,

I think this is still present.
http://192.168.134.197/CerberusQA/ReportingExecutionByTag.jsp?Tag=CERBERUS_TESTS_VCCRM_20170308
5 PE executions
